blank_issues_enabled: false
contact_links:
  - name: Object Collab discussion
    url: https://github.com/UniqueName54321/Collabject/discussions
    about: Ask questions, propose ideas, or discuss unfinished integrations.